Yu/fix/review status
thinc-org/cugetreg-backend pull request #84
Opened 2021-12-04 09:18 UTC by saenyakorn

## What I do
- เปลี่ยนชื่อจาก `Status` -> `ReviewStatus` เพราะ `Status` เฉยๆ มัน general เกินไป
- เปลี่ยนชื่อจาก `Interaction` -> `ReviewInteractionType` เนื่องด้วยเหตุผลเดียวกัน
- เวลา reject review จะไป Update review status ให้เป็น REJECTED แทนที่จะลบทิ้ง 
- เวลาแก้ไข Review จะ set status ให้เป็น PENDING เสมอ (เพราะเราสามารถแก้ไข Rejected Review ได้)
- เวลาเรียก MyPendingReview จะเอาทั้ง review ที่ติดสถานะ PENDING, REJECTED มาด้วย
- พยายามใช้ enum แทนจุดที่ใช้ string ตรงๆ (ทำไม่ครบ แต่ทำแค่ในส่วนที่เกี่ยวข้อง)

## Demo 
https://dev.cugetreg.com/S/courses/0201122

2021-12-04 18:21 UTC, saenyakorn commented
related to https://github.com/thinc-org/cugetreg-frontend/pull/270

2021-12-05 07:54 UTC, bombnp requested changes
some minor changes, other than that, LGTM

2021-12-05 07:54 UTC, bombnp commented on src/review/review.graphql
> +  setInteraction(
should this be `setReviewInteraction`?

2021-12-05 07:54 UTC, bombnp commented on src/review/review.graphql
> +    interaction: ReviewInteractionType!
change to `interactionType`?

2021-12-05 07:54 UTC, bombnp commented on src/review/review.graphql
> +    interaction: ReviewInteractionType!
will need to change other related codes too

2021-12-05 07:54 UTC, bombnp commented on src/review/review.service.ts
> +        message: 'Only APPROVED status is not supported',
```suggestion
        message: 'APPROVED reviews can not be edited!',
```

2021-12-05 07:54 UTC, bombnp commented on src/review/review.service.ts
> +  async setStatus(reviewId: string, status: ReviewStatus): Promise<string> {
just remove `setStatus` entirely and move input validation to `changeStatus`

2021-12-05 12:43 UTC, bombnp requested changes
ONE more change
just merge after fix

2021-12-05 12:43 UTC, bombnp commented on src/review/review.service.ts
>      }
use guard clause pattern instead to remain consistent
```ts
async setStatus(reviewId: string, status: ReviewStatus): Promise<string> {
  if (!(status in ReviewStatus)) {
    throw new BadRequestException({
      reason: 'INVALID_STATUS',
      message: 'Only APPROVED and REJECTED status is supported',
      message: 'APPROVED reviews can not be edited!',
    })
  }

  await this.changeStatus(reviewId, status)
  const review = await this.reviewModel.findByIdAndUpdate(reviewId, {
    $set: {
      status,
    },
  })
  if (!review) {
    throw new NotFoundException({
      reason: 'REVIEW_NOT_FOUND',
      message: `Error approving review ${reviewId}: Review not found`,
    })
  }
  return 'Review status updated successfully'
}
```

2021-12-05 13:00 UTC, bombnp commented on src/review/review.service.ts
> +        message: `Error approving review ${reviewId}: Review not found`,
```suggestion
        message: `Error setting status for review ${reviewId}: Review not found`,
```

2021-12-05 13:01 UTC, bombnp approved these changes

2021-12-05 13:02 UTC, merged